from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

import pytest
import sqlalchemy as sa
from pydantic import BaseModel, ConfigDict
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from maple_chat.agent.service import (
    AgentNotConfiguredService,
    DurableAgentService,
    NexonAgentService,
)
from maple_chat.agent.tools import ToolRegistry, ToolSpec
from maple_chat.db.models import AgentRun, AgentToolCall, AnswerMode, RunState
from maple_chat.llm.client import ChatMessage, LLMUnavailable
from maple_chat.qa.service import QuestionRequest


class _EmptyInput(BaseModel):
    model_config = ConfigDict(extra="forbid")


class _FinishGenerator:
    async def generate(self, messages: tuple[ChatMessage, ...], *, max_tokens: int = 1024) -> str:
        return '{"action":"finish","answer":"공식 캐릭터 조회 결과입니다."}'


class _UnavailableGenerator:
    async def generate(self, messages: tuple[ChatMessage, ...], *, max_tokens: int = 1024) -> str:
        raise LLMUnavailable("test")


class _ScriptedGenerator:
    def __init__(self, responses: list[str | Exception]) -> None:
        self.responses = responses

    async def generate(self, messages: tuple[ChatMessage, ...], *, max_tokens: int = 1024) -> str:
        response = self.responses.pop(0)
        if isinstance(response, Exception):
            raise response
        return response


def _empty_registry() -> ToolRegistry:
    async def handler(_: BaseModel) -> dict[str, Any]:
        return {}

    return ToolRegistry(
        (
            ToolSpec(
                name="unused",
                description="unused",
                input_model=_EmptyInput,
                handler=handler,
            ),
        )
    )


def _request(message_id: int) -> QuestionRequest:
    return QuestionRequest(
        guild_id=1,
        channel_id=10,
        request_message_id=message_id,
        requester_hash="requester-hash",
        query="캐릭터를 분석해줘",
        received_at=datetime(2026, 8, 31, tzinfo=UTC),
    )


@pytest.mark.asyncio
async def test_agent_answer_is_persisted_and_duplicate_is_noop(
    factory: async_sessionmaker[AsyncSession],
) -> None:
    service = NexonAgentService(_FinishGenerator(), _empty_registry())

    async with factory() as session, session.begin():
        outcome = await service.answer(session, _request(501))
    async with factory() as session, session.begin():
        duplicate = await service.answer(session, _request(501))

    assert outcome.mode is AnswerMode.DIRECT
    assert "공식 캐릭터 조회 결과" in outcome.text
    assert "Generated by Maple Chat Agent without external tool data" in outcome.text
    assert duplicate.duplicate is True
    assert duplicate.answer_id == outcome.answer_id


@pytest.mark.asyncio
async def test_agent_unavailable_and_missing_key_responses_are_persisted(
    factory: async_sessionmaker[AsyncSession],
) -> None:
    unavailable = NexonAgentService(_UnavailableGenerator(), _empty_registry())

    async with factory() as session, session.begin():
        unavailable_outcome = await unavailable.answer(session, _request(502))
    missing_service = AgentNotConfiguredService(factory)
    missing_outcome = await missing_service.answer(_request(503))
    duplicate = await missing_service.answer(_request(503))

    assert "사용할 수 없습니다" in unavailable_outcome.text
    assert unavailable_outcome.metrics is not None
    assert unavailable_outcome.metrics.model_calls == 0
    assert "NEXON_API_KEY" in missing_outcome.text
    assert duplicate.duplicate is True


@pytest.mark.asyncio
async def test_durable_agent_persists_plan_and_success(
    factory: async_sessionmaker[AsyncSession],
) -> None:
    generator = _ScriptedGenerator(
        [
            '{"goal":"캐릭터 분석","steps":["공식 정보 조회","요약"]}',
            '{"action":"finish","answer":"분석을 완료했습니다."}',
        ]
    )
    service = DurableAgentService(factory, NexonAgentService(generator, _empty_registry()))

    outcome = await service.answer(_request(510))
    duplicate = await service.answer(_request(510))

    async with factory() as session:
        run = await session.scalar(sa.select(AgentRun).where(AgentRun.request_message_id == 510))
    assert run is not None
    assert run.state is RunState.SUCCEEDED
    assert run.plan_json["goal"] == "캐릭터 분석"
    assert "Agent 실행 ID" in outcome.text
    assert duplicate.duplicate is True


@pytest.mark.asyncio
async def test_failed_durable_agent_resumes_from_tool_checkpoint(
    factory: async_sessionmaker[AsyncSession],
) -> None:
    executed = 0

    class _LookupInput(BaseModel):
        value: str

    async def lookup(value: BaseModel) -> dict[str, Any]:
        nonlocal executed
        executed += 1
        parsed = _LookupInput.model_validate(value)
        return {"level": 290, "character": parsed.value}

    registry = ToolRegistry(
        (
            ToolSpec(
                name="lookup",
                description="조회",
                input_model=_LookupInput,
                handler=lookup,
            ),
        )
    )
    generator = _ScriptedGenerator(
        [
            '{"goal":"캐릭터 분석","steps":["조회","요약"]}',
            '{"action":"tool","tool":"lookup","arguments":{"value":"테스트"}}',
            LLMUnavailable("local generation unavailable"),
        ]
    )
    service = DurableAgentService(factory, NexonAgentService(generator, registry, max_tool_calls=2))

    failed = await service.answer(_request(511))
    async with factory() as session:
        run = await session.scalar(sa.select(AgentRun).where(AgentRun.request_message_id == 511))
        assert run is not None
        calls = tuple(
            await session.scalars(
                sa.select(AgentToolCall).where(AgentToolCall.run_id == run.run_id)
            )
        )
    assert run.state is RunState.FAILED
    assert len(calls) == 1
    assert "--agent-resume" in failed.text

    generator.responses.append('{"action":"finish","answer":"저장된 조회 결과로 완료했습니다."}')
    resumed = await service.answer(_request(512), resume_run_id=run.run_id)

    async with factory() as session:
        refreshed = await session.get(AgentRun, run.run_id)
        call_count = await session.scalar(
            sa.select(sa.func.count())
            .select_from(AgentToolCall)
            .where(AgentToolCall.run_id == run.run_id)
        )
    assert refreshed is not None
    assert refreshed.state is RunState.SUCCEEDED
    assert refreshed.resume_count == 1
    assert call_count == 1
    assert executed == 1
    assert "저장된 조회 결과" in resumed.text
