"""g002 durable schema

Revision ID: g002_schema
Revises:
Create Date: 2026-08-04 17:25:00.183541
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "g002_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("answer_id", sa.String(length=36), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("request_message_id", sa.BigInteger(), nullable=False),
        sa.Column("response_message_id", sa.BigInteger(), nullable=True),
        sa.Column("requester_hash", sa.String(length=128), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "generated",
                "retrieval_only",
                "insufficient_evidence",
                name="answer_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("answer_id"),
        sa.UniqueConstraint("request_message_id"),
        sa.UniqueConstraint("response_message_id"),
    )
    op.create_table(
        "boards",
        sa.Column("board_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "crawl_checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("board_id"),
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "article",
                "comment",
                "ocr",
                name="chunk_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_key", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chunking_revision", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("source_type", "source_key", "ordinal", "chunking_revision"),
    )
    op.create_index(
        "ix_chunks_active", "chunks", ["active"], unique=False, postgresql_where=sa.text("active")
    )
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=256), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "leased",
                "succeeded",
                "dead_letter",
                name="job_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_crawl_jobs_ready", "crawl_jobs", ["state", "next_attempt_at", "priority"], unique=False
    )
    op.create_index(
        "uq_crawl_jobs_active_dedupe",
        "crawl_jobs",
        ["job_type", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("state IN ('queued', 'leased')"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_type", sa.String(length=32), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "partial",
                "succeeded",
                "failed",
                "cancelled",
                name="run_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "counters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "denylist",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=True),
        sa.Column("source_key", sa.String(length=160), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("actor_hash", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_denylist_active_source",
        "denylist",
        ["source_key"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "embedding_revisions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_commit", sa.String(length=128), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("normalized", sa.Boolean(), nullable=False),
        sa.Column("distance", sa.String(length=32), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "uq_embedding_revisions_single_active",
        "embedding_revisions",
        [sa.literal_column("(true)")],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "guild_settings",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("allowed_channel_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "allowed_role_ids",
            postgresql.ARRAY(sa.BigInteger()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("aggregate_key", sa.String(length=256), nullable=False),
        sa.Column("dedupe_key", sa.String(length=320), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_table(
        "tombstones",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "article",
                "comment",
                "ocr",
                name="tombstone_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_key", sa.String(length=160), nullable=False),
        sa.Column("deleted_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "source_key"),
    )
    op.create_table(
        "answer_sources",
        sa.Column("answer_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("retrieval_score", sa.Float(), nullable=False),
        sa.Column("rerank_score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["answer_id"], ["answers.answer_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.chunk_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("answer_id", "chunk_id"),
        sa.UniqueConstraint("answer_id", "rank"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("board_id", sa.BigInteger(), nullable=False),
        sa.Column("remote_name", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["boards.board_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("board_id", "remote_name"),
    )
    op.create_table(
        "chunk_embeddings",
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("revision_id", sa.BigInteger(), nullable=False),
        sa.Column("embedding", Vector(dim=1024), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.chunk_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revision_id"], ["embedding_revisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("chunk_id", "revision_id"),
    )
    op.create_index(
        "ix_chunk_embeddings_hnsw",
        "chunk_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("answer_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("actor_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5"),
        sa.ForeignKeyConstraint(["answer_id"], ["answers.answer_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("board_id", sa.BigInteger(), nullable=False),
        sa.Column("remote_article_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author_hash", sa.String(length=128), nullable=True),
        sa.Column("sanitized_body", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("view_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("recommendation_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "fetched",
                "parsed",
                "sanitized",
                "chunked",
                "indexed",
                "retryable_failed",
                "terminal_failed",
                "deleted",
                "denied",
                name="source_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.board_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("board_id", "remote_article_id"),
    )
    op.create_index(
        "ix_articles_active_board",
        "articles",
        ["board_id"],
        unique=False,
        postgresql_where=sa.text("status = 'indexed'"),
    )
    op.create_index(
        "ix_articles_body_trgm",
        "articles",
        ["sanitized_body"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sanitized_body": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_articles_title_trgm",
        "articles",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("remote_comment_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_remote_comment_id", sa.BigInteger(), nullable=True),
        sa.Column("author_hash", sa.String(length=128), nullable=True),
        sa.Column("sanitized_body", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "fetched",
                "parsed",
                "sanitized",
                "chunked",
                "indexed",
                "retryable_failed",
                "terminal_failed",
                "deleted",
                "denied",
                name="comment_source_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "remote_comment_id"),
    )
    op.create_index(
        "ix_comments_article_active",
        "comments",
        ["article_id"],
        unique=False,
        postgresql_where=sa.text("status = 'indexed'"),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_url_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fetch_status", sa.String(length=32), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "source_url_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media_assets")
    op.drop_index(
        "ix_comments_article_active",
        table_name="comments",
        postgresql_where=sa.text("status = 'indexed'"),
    )
    op.drop_table("comments")
    op.drop_index(
        "ix_articles_title_trgm",
        table_name="articles",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_articles_body_trgm",
        table_name="articles",
        postgresql_using="gin",
        postgresql_ops={"sanitized_body": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_articles_active_board",
        table_name="articles",
        postgresql_where=sa.text("status = 'indexed'"),
    )
    op.drop_table("articles")
    op.drop_table("feedback")
    op.drop_index(
        "ix_chunk_embeddings_hnsw",
        table_name="chunk_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("active"),
    )
    op.drop_table("chunk_embeddings")
    op.drop_table("categories")
    op.drop_table("answer_sources")
    op.drop_table("tombstones")
    op.drop_table("outbox_events")
    op.drop_table("guild_settings")
    op.drop_index(
        "uq_embedding_revisions_single_active",
        table_name="embedding_revisions",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("embedding_revisions")
    op.drop_index(
        "uq_denylist_active_source", table_name="denylist", postgresql_where=sa.text("active")
    )
    op.drop_table("denylist")
    op.drop_table("crawl_runs")
    op.drop_index(
        "uq_crawl_jobs_active_dedupe",
        table_name="crawl_jobs",
        postgresql_where=sa.text("state IN ('queued', 'leased')"),
    )
    op.drop_index("ix_crawl_jobs_ready", table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_index("ix_chunks_active", table_name="chunks", postgresql_where=sa.text("active"))
    op.drop_table("chunks")
    op.drop_table("boards")
    op.drop_table("answers")
    # ### end Alembic commands ###
