"""g004 chunk lexical index

Revision ID: g004_chunk_lexical
Revises: g002_schema
Create Date: 2026-08-04 17:36:10.183517
"""

from collections.abc import Sequence

from alembic import op

revision: str = "g004_chunk_lexical"
down_revision: str | Sequence[str] | None = "g002_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_chunks_text_trgm",
        "chunks",
        ["text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chunks_text_trgm",
        table_name="chunks",
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
