"""g006 active run overlap guard

Revision ID: g006_run_overlap
Revises: g005_audit_events
Create Date: 2026-08-04 17:46:57.358445
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "g006_run_overlap"
down_revision: str | Sequence[str] | None = "g005_audit_events"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_crawl_runs_active_type",
        "crawl_runs",
        ["run_type"],
        unique=True,
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_crawl_runs_active_type",
        table_name="crawl_runs",
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    # ### end Alembic commands ###
