from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any

import pytest
from pydantic import BaseModel, ConfigDict, Field

from maple_chat.agent.service import AgentPlanningError, AgentStep, NexonAgentService
from maple_chat.agent.tools import ToolRegistry, ToolSpec
from maple_chat.llm.client import ChatMessage


class _Args(BaseModel):
    model_config = ConfigDict(extra="forbid")

    value: str = Field(min_length=1)


class _SequenceGenerator:
    def __init__(self, responses: tuple[str, ...]) -> None:
        self.responses = list(responses)
        self.calls: list[tuple[ChatMessage, ...]] = []

    async def generate(self, messages: tuple[ChatMessage, ...], *, max_tokens: int = 1024) -> str:
        self.calls.append(messages)
        return self.responses.pop(0)


def _registry(
    handler: Callable[[BaseModel], Awaitable[dict[str, Any]]],
    *,
    name: str = "lookup",
) -> ToolRegistry:
    return ToolRegistry(
        (
            ToolSpec(
                name=name,
                description="테스트 조회",
                input_model=_Args,
                handler=handler,
            ),
        )
    )


@pytest.mark.asyncio
async def test_agent_chooses_tool_evaluates_result_and_finishes() -> None:
    calls: list[str] = []

    async def handler(value: BaseModel) -> dict[str, Any]:
        args = _Args.model_validate(value)
        calls.append(args.value)
        return {"official_value": 290}

    generator = _SequenceGenerator(
        (
            '{"action":"tool","tool":"get_character_basic","arguments":{"value":"캐릭터"}}',
            '{"action":"finish","answer":"공식 조회 레벨은 290입니다."}',
        )
    )
    service = NexonAgentService(
        generator,
        _registry(handler, name="get_character_basic"),
        max_tool_calls=2,
    )

    result = await service.run("캐릭터 레벨을 알려줘")

    assert calls == ["캐릭터"]
    assert len(result.steps) == 1
    assert result.steps[0].result == {"official_value": 290}
    assert "공식 조회 레벨은 290" in result.text
    assert result.text.endswith("Data based on NEXON Open API")
    assert "official_value" in generator.calls[1][-1].content


@pytest.mark.asyncio
async def test_agent_rejects_invalid_decisions_after_bounded_correction() -> None:
    async def handler(_: BaseModel) -> dict[str, Any]:
        raise AssertionError("invalid plan must not execute a tool")

    generator = _SequenceGenerator(("not-json", '{"action":"finish"}'))
    service = NexonAgentService(generator, _registry(handler), max_tool_calls=2)

    result = await service.run("질문")

    assert len(generator.calls) == 2
    assert result.steps == ()
    assert "안전한 실행 계획" in result.text


@pytest.mark.asyncio
async def test_agent_blocks_identical_tool_call_and_enforces_call_limit() -> None:
    executed = 0

    async def handler(value: BaseModel) -> dict[str, Any]:
        nonlocal executed
        executed += 1
        return {"value": _Args.model_validate(value).value}

    same = '{"action":"tool","tool":"lookup","arguments":{"value":"x"}}'
    generator = _SequenceGenerator(
        (same, same, '{"action":"finish","answer":"반복 호출을 중단했습니다."}')
    )
    service = NexonAgentService(generator, _registry(handler), max_tool_calls=2)

    result = await service.run("질문")

    assert executed == 1
    assert len(result.steps) == 2
    assert "반복할 수 없습니다" in str(result.steps[1].result)
    assert len(generator.calls) == 3


def test_agent_rejects_invalid_tool_call_limits() -> None:
    generator = _SequenceGenerator(())

    async def handler(_: BaseModel) -> dict[str, Any]:
        return {}

    registry = _registry(handler)
    with pytest.raises(ValueError, match="between one and eight"):
        NexonAgentService(generator, registry, max_tool_calls=0)
    with pytest.raises(ValueError, match="between one and eight"):
        NexonAgentService(generator, registry, max_tool_calls=9)


@pytest.mark.asyncio
async def test_agent_replaces_model_supplied_attribution_with_observed_provenance() -> None:
    async def handler(_: BaseModel) -> dict[str, Any]:
        return {}

    generator = _SequenceGenerator(
        ('```json\n{"action":"finish","answer":"완료\\n\\nData based on NEXON Open API"}\n```',)
    )
    service = NexonAgentService(generator, _registry(handler))

    result = await service.run("질문")

    assert "Data based on NEXON Open API" not in result.text
    assert result.text.count("Generated by Maple Chat Agent without external tool data") == 1


@pytest.mark.asyncio
async def test_agent_attribution_matches_local_tool_provenance() -> None:
    async def handler(value: BaseModel) -> dict[str, Any]:
        return {"value": _Args.model_validate(value).value}

    generator = _SequenceGenerator(
        (
            '{"action":"tool","tool":"query_knowledge_graph","arguments":{"value":"제논"}}',
            '{"action":"finish","answer":"제논은 두 계열에 속합니다."}',
        )
    )
    service = NexonAgentService(
        generator,
        _registry(handler, name="query_knowledge_graph"),
        max_tool_calls=2,
    )

    result = await service.run("제논의 직업 계열은?")

    assert result.text.endswith("Data based on Maple Chat knowledge graph")
    assert "Data based on NEXON Open API" not in result.text


@pytest.mark.asyncio
async def test_agent_returns_safe_fallback_when_forced_finish_is_invalid() -> None:
    async def handler(value: BaseModel) -> dict[str, Any]:
        return {"value": _Args.model_validate(value).value}

    generator = _SequenceGenerator(
        (
            '{"action":"tool","tool":"lookup","arguments":{"value":"x"}}',
            "not-json",
        )
    )
    service = NexonAgentService(generator, _registry(handler), max_tool_calls=1)

    result = await service.run("질문")

    assert "안전한 형식으로 생성하지 못했습니다" in result.text


@pytest.mark.asyncio
async def test_agent_builds_bounded_plan_with_one_correction() -> None:
    async def handler(_: BaseModel) -> dict[str, Any]:
        return {}

    generator = _SequenceGenerator(
        (
            "invalid",
            '{"goal":"하드 보스 준비","steps":["캐릭터 조회","근거 비교"]}',
        )
    )
    service = NexonAgentService(generator, _registry(handler))

    result = await service.plan("보스 준비를 도와줘")

    assert result.plan.goal == "하드 보스 준비"
    assert result.plan.steps == ["캐릭터 조회", "근거 비교"]
    assert len(generator.calls) == 2


@pytest.mark.asyncio
async def test_agent_plan_failure_is_bounded() -> None:
    async def handler(_: BaseModel) -> dict[str, Any]:
        return {}

    service = NexonAgentService(
        _SequenceGenerator(("invalid", '{"goal":"x","steps":[]}')),
        _registry(handler),
    )

    with pytest.raises(AgentPlanningError, match="유효한 작업 계획"):
        await service.plan("질문")


@pytest.mark.asyncio
async def test_agent_reconstructs_prior_steps_without_repeating_tool() -> None:
    executions = 0

    async def handler(_: BaseModel) -> dict[str, Any]:
        nonlocal executions
        executions += 1
        return {}

    generator = _SequenceGenerator(
        ('{"action":"finish","answer":"저장된 조회 결과로 완료했습니다."}',)
    )
    service = NexonAgentService(generator, _registry(handler), max_tool_calls=2)
    previous = AgentStep(1, "lookup", {"value": "x"}, {"official_value": 290})

    result = await service.run("질문", prior_steps=(previous,))

    assert executions == 0
    assert len(result.steps) == 1
    assert "official_value" in generator.calls[0][-1].content
